### ISSUE TITLE
Bump version for pypi

### ISSUE THREAD

**Issue by kapoorlab** [Sentinal4D/cellshape-cloud#14]
**Is your feature request related to a problem? Please describe.**
Bump in the pypi version for the latest PR's to take effect.

**Describe the solution you'd like**
New versions of cellshape-cloud and cellshape-cluster that incorporates the changes made in this [PR](https://github.com/Sentinal4D/cellshape-cloud/pull/12) and this [PR](https://github.com/Sentinal4D/cellshape-cluster/pull/6) be made available when users are installing the package via pypi.

**Describe alternatives you've considered**
Currently am doing local package installation via my forks for the codes to run on my side.

**Additional context**
When do you usually make new releases, is there a schedule or is this based on making the new changes available to the users?

**Comment by DeVriesMatt** [comment]
Hi @kapoorlab, thank you for your issue! 

I make new releases based on making new changes. I will set up a schedule so that this is more on time with any changes collaborators such as yourself will make. 

These changes made should now be incorporated into the most recent version (cellshape-cloud==0.1.2 at commit [84ec1be](https://github.com/Sentinal4D/cellshape-cloud/commit/84ec1bed0b2d8dcecafaf30a987c693863b5cf3c) , cellshape-cluster==0.0.18 at commit [7168ed5](https://github.com/Sentinal4D/cellshape-cluster/commit/7168ed59f075671236370a31759d29ca732f28f3)). Please let me know if you have any suggestions on keeping up to date with this. :smile:
